package com.linyi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
//@MapperScan("com.linyi.mapper")
public class Application {
	
    public static void main(String[] args) {  
        SpringApplication.run(Application.class, args);  
    } 
}
