spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: 127.0.0.1
        healthCheckPath: /health
        healthCheckInterval: 15s
        serviceName: consul001
#        instance-id: consul001
  application:
    name: consul001
server:
  port: 8503